export const columns = [
  {
    ColId: "EmployeeCode",
    ColName: "MÃ NHÂN VIÊN",
    ColWidth: 143,
    ColFixed: true,
    ColPosFixed: "left",
    ColAlignment: "left",
  },
  {
    ColId: "FullName",
    ColName: "TÊN NHÂN VIÊN",
    ColWidth: 250,
    ColFixed: true,
    ColPosFixed: "left",
    ColAlignment: "left",
  },
  {
    ColId: "GenderName",
    ColName: "GIỚI TÍNH",
    ColWidth: 105,
    ColFixed: false,
    ColAlignment: "left",
  },
  {
    ColId: "DateOfBirth",
    ColName: "NGÀY SINH",
    ColWidth: 150,
    ColFixed: false,
    ColAlignment: "center",
  },
  {
    ColId: "IdentityNumber",
    ColName: "SỐ CMND",
    ColWidth: 200,
    ColFixed: false,
    ColAlignment: "left",
  },
  {
    ColId: "PositionName",
    ColName: "CHỨC DANH",
    ColWidth: 250,
    ColFixed: false,
    ColAlignment: "left",
  },
  {
    ColId: "DepartmentName",
    ColName: "TÊN ĐƠN VỊ",
    ColWidth: 250,
    ColFixed: false,
    ColAlignment: "left",
  },
  {
    ColId: "BankAccount",
    ColName: "SỐ TÀI KHOẢN",
    ColWidth: 150,
    ColFixed: false,
    ColAlignment: "left",
  },
  {
    ColId: "BankName",
    ColName: "TÊN NGÂN HÀNG",
    ColWidth: 250,
    ColFixed: false,
    ColAlignment: "left",
  },
  {
    ColId: "BankBranch",
    ColName: "CHI NHÁNH NGÂN HÀNG",
    ColWidth: 250,
    ColFixed: false,
    ColAlignment: "left",
  },
  {
    ColId: "Function",
    ColName: "CHỨC NĂNG",
    ColWidth: 120,
    ColFixed: true,
    ColPosFixed: "right",
    ColAlignment: "center",
    ColCellTemplate: "functionCell",
  },
];
