export const EmployeeModel = {
  EmployeeCode: null,
  FirstName: null,
  Gender: null,
  DateOfBirth: null,
  Email: null,
  Address: null,
  MobilePhoneNumber: null,
  TelephoneNumber: null,
  IdentityNumber: null,
  IdentityDate: null,
  IdentityPlace: null,
  DepartmentId: null,
  PositionName: null,
  BankAccount: null,
  BankName: null,
  BankBranch: null,
};
