export const ListMenuItem = [
  {
    id: 1,
    link: "/dashboard",
    label: "Tổng quan",
    iconName: "icon-dashboard",
  },
  {
    id: 2,
    link: "/cash",
    label: "Tiền mặt",
    iconName: "icon-cash",
  },
  {
    id: 3,
    link: "/bank",
    label: "Tiền gửi",
    iconName: "icon-bank",
  },
  {
    id: 4,
    link: "/purchase",
    label: "Mua hàng",
    iconName: "icon-purchase",
  },
  {
    id: 5,
    link: "/sale",
    label: "Bán hàng",
    iconName: "icon-sale",
  },
  {
    id: 6,
    link: "/invoice",
    label: "Quản lý hóa đơn",
    iconName: "icon-invoice",
  },
  {
    id: 7,
    link: "/stock",
    label: "Kho",
    iconName: "icon-stock",
  },
  {
    id: 8,
    link: "/tools",
    label: "Công cụ dụng cụ",
    iconName: "icon-tools",
  },
  {
    id: 9,
    link: "/assets",
    label: "Tài sản cố định",
    iconName: "icon-fixed-assets",
  },
  {
    id: 10,
    link: "/tax",
    label: "Thuế",
    iconName: "icon-tax",
  },
  {
    id: 11,
    link: "/price",
    label: "Giá thành",
    iconName: "icon-price",
  },
  {
    id: 12,
    link: "/general",
    label: "Tổng hợp",
    iconName: "icon-general",
  },
  {
    id: 13,
    link: "/budget",
    label: "Ngân sách",
    iconName: "icon-budget",
  },
  {
    id: 14,
    link: "/report",
    label: "Báo cáo",
    iconName: "icon-report",
  },
  {
    id: 15,
    link: "/finance",
    label: "Phân tích tài chính",
    iconName: "icon-finance",
  },
];
